name: Sync to Hugging Face hub
'on':
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Pull latest changes from Hugging Face
        env:
          HF_write_token: ${{ secrets.HF_write_token }}
        run: |
          # Formatted URL to bypass the password deprecation check
          git remote add space https://hf:${HF_write_token}@huggingface.co/spaces/bharambesapana/SB_HuggingFace_repo
          git fetch space main
          git merge space/main --allow-unrelated-histories --strategy-option=theirs

      - name: Push to hub
        env:
          HF_write_token: ${{ secrets.HF_write_token }}
        run: |
          git push space main
